### model
model_name_or_path: Model/glm-4-9b-chat
template: glm-4

### dataset
data_path: train.json
cutoff_len: 8192
preprocessing_num_workers: 16

### output
output_dir: glm-4/sft_193
logging_steps: 10
logging_first_step: true
save_steps: 500
overwrite_output_dir: true

### train
deepspeed_path: train/deepspeed_zero_stage2_config.json
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
gradient_checkpointing: true
learning_rate: 2.0e-5
num_train_epochs: 1
lr_scheduler_type: WarmupLR
warmup_ratio: 0.05
lora_rank: 8
lora_dropout: 0.05
lora_alpha: 16
fp16: true
ddp_timeout: 180000000
swanlab:
  project: "glm4-fintune"
  experiment_name: "glm-4-9b-chat"
  description: "使用glm-4-9b-chat模型在肝器官数据集上微调。"
  config:
    model: "glm-4-9b-chat"
    dataset: "liver_dataset"

